# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 246c1a1710329d19b279a171485c038cba30a021b4f9b7b83ed416c0f42224711e0257aabcaf85539e9df55e22cc9941bd9f4a23147aa1d55b4d3f3a568e393c

test:
  secret_key_base: f0859a62460f72195620b12ba74bfbe7cfa80fdd76a8b005eabf7d6b1b303d638607c3a52d29bbd0e9f6bfca4464da549722fdc47762ddc097eecb0e5a9659e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
